version: '3.8'

services:
  account:
    build:
      context: .
      dockerfile: ./account/app.dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=accountdb
      - DB_USER=accountuser
      - DB_PASSWORD=accountpassword
    depends_on:
      - db
    networks:
      - logilo-network

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=accountdb
      - POSTGRES_USER=accountuser
      - POSTGRES_PASSWORD=accountpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - logilo-network

volumes:
  postgres_data:

networks:
  logilo-network:
    driver: bridge
