version: '3.8'
services:
  shopify-db:
    image: postgres:16
    env_file:
      - .env.development  # Ensure this file exists with DB credentials
    environment:
      POSTGRES_USER: shopify_user_dev
      POSTGRES_PASSWORD: shopify_password_dev
      POSTGRES_DB: shopify_db_dev
    volumes:
      - shopify_postgres_data:/var/lib/postgresql/data
    networks:
      - shopify-network
    restart: always

  shopify-service:
    build:
      context: .  # Path to your service's Go code
      dockerfile: ./shopify/app.dockerfile
    env_file:
      - .env.development  # Make sure your environment variables are set
    depends_on:
      - shopify-db  # Ensure the DB is up before starting the service
    networks:
      - shopify-network
    ports:
      - "8080:8080"  # Adjust if your service runs on different ports
    
  account-db:
    image: postgres:16
    env_file:
      - .env.development  # Ensure this file exists with DB credentials
    environment:
      POSTGRES_USER: account_user_dev
      POSTGRES_PASSWORD: account_password_dev
      POSTGRES_DB: account_db_dev
    volumes:
      - account_postgres_data:/var/lib/postgresql/data
    networks:
      - shopify-network
    restart: always

  account-service:
    build:
      context: .  # Path to your service's Go code
      dockerfile: ./account/app.dockerfile
    env_file:
      - .env.development  # Make sure your environment variables are set
    depends_on:
      - account-db  # Ensure the DB is up before starting the service
    networks:
      - shopify-network
    ports:
      - "8081:8081"  # Adjust if your service runs on different ports


volumes:
  shopify_postgres_data:
  account_postgres_data:
networks:
  shopify-network:
    driver: bridge
