name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]  # The name of the CI pipeline workflow
    types:
      - completed  # Trigger when CI workflow completes

jobs:
  deploy:
    name: Deploy to Production
    runs-on: self-hosted

    steps:
      - name: Pulls Docker image
        run: sudo docker pull logilog/graphql:latest
      - name : Delete Old container
        run: sudo docker rm -f graphql-container || true
      - name: run the container
        run: sudo docker run -d -p 8084:8084 --name graphql-container logilog/graphql

      - name: Pulls Docker image
        run: sudo docker pull logilog/account-db:latest
      - name : Delete Old container
        run: sudo docker rm -f account-db-container || true
      - name: run the container
        run: sudo docker run -d -p 5432:5432 --name account-db-container logilog/account-db

        
      - name: Pulls Docker image
        run: sudo docker pull logilog/shopify-db:latest
      - name : Delete Old container
        run: sudo docker rm -f shopify-db-container || true
      - name: run the container
        run: sudo docker run -d -p 5432:5432 --name shopify-db-container logilog/shopify-db

        
      - name: Pulls Docker image
        run: sudo docker pull logilog/account-service:latest
      - name : Delete Old container
        run: sudo docker rm -f account-service-container || true
      - name: run the container
        run: sudo docker run -d -p 8081:8081 --name account-service-container logilog/account-service

      - name: Pulls Docker image
        run: sudo docker pull logilog/shopify-service:latest
      - name : Delete Old container
        run: sudo docker rm -f shopify-service-container || true
      - name: run the container
        run: sudo docker run -d -p 8080:8080 --name shopify-service-container logilog/shopify-service
