name: Docker Compose CI/CD

on:
  push:
    branches: 
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Log in to Docker Hub (if needed for deployment)
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Build the Docker images using docker-compose
    - name: Build Docker Compose Services
      run: |
        docker-compose -f docker-compose.yaml build

    # Tag and push the images to Docker Hub
    - name: Build and Push Docker Compose Services
      run: |
        services=$(docker-compose -f docker-compose.yaml config --services)
        for service in $services; do
          # Tag each service image with the Docker Hub username
          docker tag $service:latest ${{ secrets.DOCKER_USERNAME }}/$service:latest
          # Push the tagged image to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/$service:latest
        done

    # Deploy the services using docker-compose
    - name: Deploy Services
      run: |
        docker-compose -f docker-compose.yaml pull
        docker-compose -f docker-compose.yaml up -d --remove-orphans
