name: CI/CD Docker Compose Deployment

on:
  push:
    branches:
      - staging  # Trigger on push to the staging branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker images and push to Docker Hub
      - name: Build and Push Docker Images
        run: |
          # Build the Docker images using docker-compose
          docker-compose build

          # Tag and push images to Docker Hub
          docker-compose push

      # Step 4: Copy docker-compose.yml to the server
      - name: Copy docker-compose.yml to Server
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/"

      # Step 5: SSH into the server to deploy the application
      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~
            docker-compose down || true  # Stop and remove any old containers
            docker-compose pull  # Pull the latest images from the Docker Hub
            docker-compose up -d  # Start containers in detached mode
