name: CI/CD Pipeline
on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate Docker tags
      id: meta
      shell: bash
      run: |
        # Get short commit SHA
        SHORT_SHA=$(git rev-parse --short HEAD)
        
        # Generate tags for each service
        echo "SHOPIFY_DB_TAGS=${{ secrets.DOCKER_USERNAME }}/shopify-db:latest,${{ secrets.DOCKER_USERNAME }}/shopify-db:$SHORT_SHA" >> $GITHUB_OUTPUT
        echo "SHOPIFY_SERVICE_TAGS=${{ secrets.DOCKER_USERNAME }}/shopify-service:latest,${{ secrets.DOCKER_USERNAME }}/shopify-service:$SHORT_SHA" >> $GITHUB_OUTPUT
        echo "GRAPHQL_SERVICE_TAGS=${{ secrets.DOCKER_USERNAME }}/graphql-service:latest,${{ secrets.DOCKER_USERNAME }}/graphql-service:$SHORT_SHA" >> $GITHUB_OUTPUT
        echo "ACCOUNT_DB_TAGS=${{ secrets.DOCKER_USERNAME }}/account-db:latest,${{ secrets.DOCKER_USERNAME }}/account-db:$SHORT_SHA" >> $GITHUB_OUTPUT
        echo "ACCOUNT_SERVICE_TAGS=${{ secrets.DOCKER_USERNAME }}/account-service:latest,${{ secrets.DOCKER_USERNAME }}/account-service:$SHORT_SHA" >> $GITHUB_OUTPUT

    - name: Build and push Shopify DB image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./shopify/db.dockerfile
        push: true
        tags: ${{ steps.meta.outputs.SHOPIFY_DB_TAGS }}

    - name: Build and push Shopify Service image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./shopify/app.dockerfile
        push: true
        tags: ${{ steps.meta.outputs.SHOPIFY_SERVICE_TAGS }}

    - name: Build and push GraphQL Service image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./graphql/app.dockerfile
        push: true
        tags: ${{ steps.meta.outputs.GRAPHQL_SERVICE_TAGS }}

    - name: Build and push Account DB image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./account/db.dockerfile
        push: true
        tags: ${{ steps.meta.outputs.ACCOUNT_DB_TAGS }}

    - name: Build and push Account Service image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./account/app.dockerfile
        push: true
        tags: ${{ steps.meta.outputs.ACCOUNT_SERVICE_TAGS }}
