name: CI/CD Pipeline
on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker meta
      id: docker-meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ secrets.DOCKER_USERNAME }}/shopify-db
          ${{ secrets.DOCKER_USERNAME }}/shopify-service
          ${{ secrets.DOCKER_USERNAME }}/graphql-service
          ${{ secrets.DOCKER_USERNAME }}/account-db
          ${{ secrets.DOCKER_USERNAME }}/account-service
        tags: |
          type=sha
          type=raw,value=latest

    - name: Build and push Shopify DB image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./shopify/db.dockerfile
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}

    - name: Build and push Shopify Service image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./shopify/app.dockerfile
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}

    - name: Build and push GraphQL Service image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./graphql/app.dockerfile
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}

    - name: Build and push Account DB image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./account/db.dockerfile
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}

    - name: Build and push Account Service image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./account/app.dockerfile
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}
