name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for Docker Hub password

    - name: Build and push Shopify DB image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./shopify/db.dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/shopify-db:latest  # Use the username from secrets

    - name: Build and push Shopify Service image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./shopify/app.dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/shopify-service:latest  # Use the username from secrets

    - name: Build and push GraphQL Service image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./graphql/app.dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/graphql-service:latest  # Use the username from secrets

    - name: Build and push Account DB image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./account/db.dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/account-db:latest  # Use the username from secrets

    - name: Build and push Account Service image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./account/app.dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/account-service:latest  # Use the username from secrets
